---
workers: {{ .Values.provisioner.workers }}
interval: {{ .Values.provisioner.interval }}
loglevel: {{ .Values.provisioner.loglevel }}
choria_insecure: {{ .Values.provisioner.insecure }}
site: {{ .Release.Name }}
{{- if .Values.prometheus.enabled }}
monitor_port: 8080
{{- end }}
{{- if .Values.jwt.enabled }}
jwt_verify_cert: /etc/choria-provisioner/signer/signer.pem
{{- end }}
logfile: /dev/stdout
helper: /helper/provision-helper
token: {{ .Values.provisioner.token }}
{{- if .Values.broker.embedded }}
{{- if .Values.auth.provisioner }}
broker_provisioning_password: {{ .Values.auth.provisioner }}
{{- end }}
{{- if .Values.auth.choria }}
broker_choria_password: {{ .Values.auth.choria }}
{{- end }}
broker_port: 4222
{{- end }}

features:
  pki: {{ .Values.pki.enabled }}
  jwt: {{ .Values.jwt.enabled }}
  broker: {{ .Values.broker.embedded }}
