---
workers: {{ .Values.provisioner.workers }}
interval: {{ .Values.provisioner.interval }}
loglevel: {{ .Values.provisioner.loglevel }}
site: {{ .Release.Name }}
{{- if .Values.prometheus.enabled }}
monitor_port: 8080
{{- end }}
{{- if .Values.jwt.enabled }}
jwt_verify_cert: /etc/choria-provisioner/signer/signer.pem
{{- end }}
logfile: /dev/stdout
helper: /helper/provision-helper
token: {{ .Values.provisioner.token }}
{{- if .Values.broker.provisionerPassword }}
broker_provisioning_password: {{ .Values.broker.provisionerPassword }}
{{- end }}
{{- if and (.Values.replicas) (gt (.Values.replicas | int) 1) }}
leader_election_name: PROVISIONER
{{- end }}
features:
  pki: {{ .Values.pki.enabled }}
  jwt: {{ .Values.jwt.enabled }}
