---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "broker.fullname" . }}
  namespace: {{ .Values.namespace }}
data:
  broker.conf: |-
{{ (tpl (.Files.Get "config/broker.conf") . ) | indent 5 }}
