---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "broker.fullname" . }}
  namespace: {{ .Release.Namespace }}
data:
  broker.conf: |-
{{ (tpl (.Files.Get "config/broker.conf") . ) | indent 5 }}
  streaming.conf: |-
{{ (tpl (.Files.Get "config/streaming.conf") . ) | indent 5 }}
