---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Values.namespace }}
  name: choria::self-enroll
rules:
  - apiGroups: ["cert-manager.io"]
    resources: ["certificaterequests", "certificaterequests", "certificaterequest"]
    verbs: ["get", "create", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: choria::self-enroll
  namespace: {{ .Values.namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ template "broker.fullname" . }}
    apiGroup: ""
roleRef:
  kind: Role
  name: choria::self-enroll
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "broker.fullname" . }}
  namespace: {{ .Values.namespace }}

