{{- if .Values.broker.createService }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "broker.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.broker.servicePort }}
      targetPort: 4222
      protocol: TCP
  {{- if .Values.broker.serviceLeafnodePort gt 0 }}
    - port: {{ .Values.broker.serviceLeafnodePort }}
      targetPort: 7422
      protocol: TCP
  {{- end }}
  selector:
    app: broker
{{- end }}
