{{- if .Values.streaming.enabled }}
{{- if .Values.streaming.storageClassName }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.streaming.pvcName }}
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.streaming.storageSize }}
  storageClassName: {{ .Values.streaming.storageClassName }}
{{- end }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "stream.fullname" . }}-ss
  namespace: {{ .Release.Namespace }}
  labels:
    app: stream
spec:
  clusterIP: None
  selector:
    app: stream

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "stream.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  serviceName: {{ template "stream.fullname" . }}-ss
  selector:
    matchLabels:
      app: stream
  template:
    metadata:
      annotations:
        {{- if .Values.prometheus.enabled }}
        prometheus.io/scrape: "true"
        prometheus.io/port: "{{ .Values.prometheus.port }}"
        prometheus.io/metric_path: "/choria/prometheus"
        {{- end }}
        {{- if .Values.podAnnotations }}
{{ toYaml .Values.podAnnotations | indent 8 }}
      {{- end }}

      labels:
        app: stream
      {{- if .Values.podLabels }}
{{ toYaml .Values.podLabels | indent 8 }}
      {{- end }}

    spec:
      serviceAccount: choria-csraccess
      serviceAccountName: choria-csraccess
      {{- if .Values.image.pullSecret }}
      imagePullSecrets:
        - name: {{ .Values.image.pullSecret }}
      {{- end }}
      {{- if .Values.securityContext.enabled }}
      securityContext:
        runAsUser: {{ .Values.securityContext.runAsUser }}
        runAsGroup: {{ .Values.securityContext.fsGroup }}
        fsGroup: {{ .Values.securityContext.fsGroup }}
      {{- end }}

      {{- if and .Values.streaming.storageInit .Values.streaming.storageClassName }}
      initContainers:
        - name: storage-init
          image: busybox
          command: ["/bin/chown", "-R", "{{ .Values.securityContext.runAsUser }}:{{ .Values.securityContext.fsGroup }}", "/data"]
          securityContext:
            runAsUser: 0
            runAsGroup: 0
          volumeMounts:
          {{- if .Values.streaming.storageClassName }}
            - mountPath: "/data"
              name: {{ .Values.streaming.pvcName }}
              readOnly: false
          {{- end }}
      {{- end }}

      containers:
      - name: stream
        image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        command: ["/bin/choria", "broker", "--config=/etc/choria/config/streaming.conf"]
        volumeMounts:
          - mountPath: "/etc/choria/config"
            name: {{ template "stream.fullname" . }}-config
            readOnly: true
        {{- if .Values.streaming.storageClassName }}
          - mountPath: "/data"
            name: {{ .Values.streaming.pvcName }}
            readOnly: false
        {{- end }}

      volumes:
        - name: {{ template "stream.fullname" . }}-config
          configMap:
            name: {{ template "broker.fullname" . }}
      {{- if .Values.streaming.storageClassName }}
        - name: {{ .Values.streaming.pvcName }}
          persistentVolumeClaim:
            claimName: {{ .Values.streaming.pvcName }}
      {{- end }}
{{- end }}
