# details about where to get the image and secret to use for it
image:
  registry: docker.io
  repository: choria/tally
  tag: 0.0.2
  pullPolicy: Always
  pullSecret: ""

# run the containers with a specific security context
securityContext:
  enabled: true
  fsGroup: 2048
  runAsUser: 2048

# additional annotations to apply to pods
podAnnotations: {}

# additional labels to apply to pods
podLabels: {}

# Tally specific settings
tally:
  # The component to watch events for
  component: "server"

  # Prefix to add to generated statistics
  prefix: "choria_tally"

  # Tally will enroll with a Cert Manager Issuer at start for
  # TLS certificates, set this to your issuer.
  certManagerIssuer: "choria-ca"

  # Service account to use for gaining access to Cert Manager
  serviceAccount: choria-csraccess

  # The level to log at
  loglevel: info

  # Port to serve prometheus metrics on
  port: 8080

  # The url to the Choria Broker
  brokerUrls: "nats://broker-ss:4222"
