---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "aaasvc.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
data:
  choria.conf: |-
{{ (tpl (.Files.Get "config/choria.conf") . ) | indent 5 }}

  config.json: |-
{{ (tpl (.Files.Get "config/config.json") . ) | indent 5 }}
