{{- if .Values.aaasvc.createIngress }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "aaasvc.fullname" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: "{{ .Values.aaasvc.ingressClass }}"
    {{- if ne .Values.aaasvc.certManagerIssuer "" }}
    cert-manager.io/cluster-issuer: "{{ .Values.aaasvc.certManagerIssuer }}"
    {{- end }}
    {{- if eq .Values.aaasvc.ingressClass "nginx "}}
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  {{- end }}

spec:
  {{- if ne .Values.aaasvc.certManagerIssuer "" }}
  tls:
    - secretName: {{ template "aaasvc.fullname" . }}-ingress
      hosts:
        - {{ required "ingressHostname is required" .Values.aaasvc.ingressHostname }}
  {{- end }}
  rules:
    - host: {{ required "ingressHostname is required" .Values.aaasvc.ingressHostname }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ template "aaasvc.fullname" . }}
                port:
                  number: 80
{{- end }}
