{{- if .Values.aaasvc.createService }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "aaasvc.fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      name: http
  selector:
    app: aaasvc
{{- end }}
