# namespace to create resources in
namespace: choria

# details about where to get the image and secret to use for it
image:
  registry: docker.io
  repository: choria/choria
  tag: latest
  pullPolicy: Always
  pullSecret: ""

# run the containers with a specific security context
securityContext:
  enabled: true
  fsGroup: 2048
  runAsUser: 2048

# additional annotations to apply to pods
podAnnotations: {}

# additional labels to apply to pods
podLabels: {}

# configures exposing of prometheus data on /metrics
prometheus:
  # enables exporting, sets annotations for prometheus discovery
  enabled: true
  # port to listen on for metrics
  port: 8080

# Broker specific settings
broker:
  # when running behind a load balancer, Service or other kind of proxy
  # the name advertised to Choria nodes should match the public reachable
  # name.  If behind those, please set this to your public DNS name
  publicName: ""

  # Choria Broker will enroll with a Cert Manager Issuer at start for
  # TLS certificates, set this to your issuer.
  certManagerIssuer: "choria-ca"

  # When true a ClusterIP service will be created exposing servicePort
  createService: false

  # The port for the Servce to expose when servicePort is true
  servicePort: 4222

  # The number of pods to create that will form a redundant cluster
  clusterSize: 1
