---
apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: {{ .Values.ca.issuerName }}
  namespace: {{ .Release.Namespace }}
spec:
  ca:
    secretName: {{ required "ca.issuerSecret is required" .Values.ca.issuerSecret }}
