---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Release.Namespace }}
  name: choria:csraccess
rules:
  - apiGroups: ["cert-manager.io"]
    resources: ["certificaterequests", "certificaterequest"]
    verbs: ["get", "create", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: choria:csracess
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: choria-csraccess
    apiGroup: ""
roleRef:
  kind: Role
  name: choria:csraccess
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: choria-csraccess
  namespace: {{ .Release.Namespace }}

