{{- if and .Values.ca.createIssuer .Values.pki.enabled }}
---
apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: {{ template "provisioner.fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
  ca:
    secretName: {{ .Values.ca.issuerSecret }}
{{- end }}
