---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "provisioner.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
data:
  client.cfg: |-
{{ (tpl (.Files.Get "config/client.cfg") . ) | indent 5 }}

  choria-provisioner.yaml: |-
{{ (tpl (.Files.Get "config/choria-provisioner.yaml") . ) | indent 4  }}

{{- if .Values.broker.createService }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "provisioner.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.broker.port }}
    targetPort: 4222
    protocol: TCP
  selector:
    app: provisioner
{{- end }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "provisioner.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: provisioner
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
      {{- if .Values.prometheus.enabled }}
        prometheus.io/scrape: "true"
        prometheus.io/port: "{{ .Values.prometheus.port }}"
      {{- end }}
      {{- if .Values.podAnnotations }}
{{ toYaml .Values.podAnnotations | indent 8 }}
      {{- end }}
      labels:
        app: provisioner
      {{- if .Values.podLabels }}
{{ toYaml .Values.podLabels | indent 8 }}
      {{- end }}
    spec:
      serviceAccount: {{ .Values.pki.serviceAccount }}
      serviceAccountName: {{ .Values.pki.serviceAccount }}
    {{- if .Values.image.pullSecret }}
      imagePullSecrets:
      - name: {{ .Values.image.pullSecret }}
    {{- end }}
    {{- if .Values.securityContext.enabled }}
      securityContext:
        runAsUser: {{ .Values.securityContext.runAsUser }}
        fsGroup: {{ .Values.securityContext.fsGroup }}
    {{- end }}
      containers:
      - name: provisioner
        image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["/usr/sbin/choria-provisioner"]
        args: ["--config", "/etc/choria-provisioner/config/choria-provisioner.yaml", "--choria-config", "/etc/choria-provisioner/config/client.cfg"]
        ports:
        - containerPort: 4222
          protocol: TCP
        volumeMounts:
        {{- if or .Values.jwt.signerSecret }}
        - name: signer
          mountPath: /etc/choria-provisioner/signer
          readOnly: true
        {{- end }}
        {{- if or .Values.broker.connectionSecret }}
        - name: ssl
          mountPath: /etc/choria-provisioner/ssl
          readOnly: true
        {{- end }}
        - name: helper
          mountPath: /helper
          readOnly: true
        - name: config
          mountPath: /etc/choria-provisioner/config
          readOnly: true

      volumes:
        {{- if or .Values.jwt.signerSecret }}
        - name: signer
          secret:
            secretName: {{ .Values.jwt.signerSecret }}
        {{- end }}
        {{- if or .Values.broker.connectionSecret }}
        - name: ssl
          secret:
            secretName: {{ .Values.broker.connectionSecret }}
        {{- end }}
        - name: config
          configMap:
            name: {{ template "provisioner.fullname" . }}-config
        - name: helper
          configMap:
            name: {{ required "helper.configMap should be set" .Values.helper.configMap }}
            defaultMode: 0755
