# details about where to get the image and secret to use for it
image:
  registry: docker.io
  repository: choria/provisioner
  tag: 0.11.0
  pullPolicy: Always
  pullSecret: ""

# run the containers with a specific security context
securityContext:
  enabled: true
  fsGroup: 2048
  runAsUser: 2048

# additional annotations to apply to pods
podAnnotations: {}

# additional labels to apply to pods
podLabels: {}

# how many instances of the service to run, requires provisioner.leader_election_name
replicas: 1

# enables the PKI integration feature which can enroll nodes into a cert-manager managed CA
pki:
  enabled: true

  # the service account used to access the Cert Manager Issuer
  serviceAccount: choria-csraccess

# configures the connection to the Choria Broker
broker:
  # url to find the Choria Broker on, localhost when embedded else a url to a remove broker
  url: ""
  # if the remote broker requires TLS this secret should hold cert.pem, key.pem and ca.pem
  connectionSecret: ""
  # password for the "provisioner" user, used to connect to the broker
  provisionerPassword: ""

# validates incoming nodes using their JWT
jwt:
  # enable JWT validation
  enabled: true
  # when enabled this secret should hold in signer.pem the public cert of the signer
  # of JWT tokens, only nodes that validate against this certificate can be provisioned
  signerSecret: jwt-signer-cert

# configures exposing of prometheus data on /metrics
prometheus:
  # enables exporting, sets annotations for prometheus discovery
  enabled: true
  # port to listen on for metrics
  port: 8080

# configures the helper used to provision nodes
helper:
  # a configMap holding the helper in provision-helper
  configMap: "provisioner-helper"

# configures the provisioner
provisioner:
  # how many concurrent provisions can be performed
  workers: 4

  # how frequently to discover provisionable machines
  interval: 5m

  # the log level to log at
  loglevel: info

  # the token used to access the provisioning agent
  token: ""

  certManagerIssuer: "choria-ca"
